public enum CurveType
{
    Linear = 0,
    InSine = 1,
    OutSine = 2,
    InOutSine = 3,
    InCubic = 4,
    OutCubic = 5,
    InOutCubic = 6,
    InQuint = 7,
    OutQuint = 8,
    InOutQuint = 9,
    InCirc = 10,
    OutCirc = 11,
    InOutCirc = 12,
    InQuad = 13,
    OutQuad = 14,
    InOutQuad = 15,
    InQuart = 16,
    OutQuart = 17,
    InOutQuart = 18,
    InExpo = 19,
    OutExpo = 20,
    InOutExpo = 21,
}
